# https://strimzi.io/install/latest?namespace=kubearmor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubearmor-kafka-cluster-operator-entity-operator-delegation
  namespace: kubearmor
  labels:
    kubearmor-app: strimzi
subjects:
  - kind: ServiceAccount
    name: kubearmor-kafka-cluster-operator
    namespace: kubearmor
roleRef:
  kind: ClusterRole
  name: kubearmor-kafka-entity-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-kafka-cluster-operator
  labels:
    kubearmor-app: strimzi
subjects:
  - kind: ServiceAccount
    name: kubearmor-kafka-cluster-operator
    namespace: kubearmor
roleRef:
  kind: ClusterRole
  name: kubearmor-kafka-cluster-operator-global
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubearmor-kafka-cluster-operator-topic-operator-delegation
  namespace: kubearmor
  labels:
    kubearmor-app: strimzi
subjects:
  - kind: ServiceAccount
    name: kubearmor-kafka-cluster-operator
    namespace: kubearmor
roleRef:
  kind: ClusterRole
  name: kubearmor-kafka-topic-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-kafka-cluster-operator
  namespace: kubearmor
  labels:
    kubearmor-app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubearmor-kafka-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: kubearmor-kafka-cluster-operator
        strimzi.io/kind: cluster-operator
      annotations:
        kubearmor-policy: audited
    spec:
      serviceAccountName: kubearmor-kafka-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
        - name: co-config-volume
          configMap:
            name: kubearmor-kafka-cluster-operator
      containers:
        - name: kubearmor-kafka-cluster-operator
          image: 'quay.io/strimzi/operator:0.23.0'
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: '120000'
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: '300000'
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: 'quay.io/strimzi/kafka:0.23.0-kafka-2.8.0'
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: 'quay.io/strimzi/kafka:0.23.0-kafka-2.8.0'
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: 'quay.io/strimzi/kafka:0.23.0-kafka-2.8.0'
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: 'quay.io/strimzi/kafka:0.23.0-kafka-2.8.0'
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.6.0=quay.io/strimzi/kafka:0.23.0-kafka-2.6.0
                2.6.1=quay.io/strimzi/kafka:0.23.0-kafka-2.6.1
                2.6.2=quay.io/strimzi/kafka:0.23.0-kafka-2.6.2
                2.7.0=quay.io/strimzi/kafka:0.23.0-kafka-2.7.0
                2.8.0=quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.6.0=quay.io/strimzi/kafka:0.23.0-kafka-2.6.0
                2.6.1=quay.io/strimzi/kafka:0.23.0-kafka-2.6.1
                2.6.2=quay.io/strimzi/kafka:0.23.0-kafka-2.6.2
                2.7.0=quay.io/strimzi/kafka:0.23.0-kafka-2.7.0
                2.8.0=quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
            - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
              value: |
                2.6.0=quay.io/strimzi/kafka:0.23.0-kafka-2.6.0
                2.6.1=quay.io/strimzi/kafka:0.23.0-kafka-2.6.1
                2.6.2=quay.io/strimzi/kafka:0.23.0-kafka-2.6.2
                2.7.0=quay.io/strimzi/kafka:0.23.0-kafka-2.7.0
                2.8.0=quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.6.0=quay.io/strimzi/kafka:0.23.0-kafka-2.6.0
                2.6.1=quay.io/strimzi/kafka:0.23.0-kafka-2.6.1
                2.6.2=quay.io/strimzi/kafka:0.23.0-kafka-2.6.2
                2.7.0=quay.io/strimzi/kafka:0.23.0-kafka-2.7.0
                2.8.0=quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |
                2.6.0=quay.io/strimzi/kafka:0.23.0-kafka-2.6.0
                2.6.1=quay.io/strimzi/kafka:0.23.0-kafka-2.6.1
                2.6.2=quay.io/strimzi/kafka:0.23.0-kafka-2.6.2
                2.7.0=quay.io/strimzi/kafka:0.23.0-kafka-2.7.0
                2.8.0=quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: 'quay.io/strimzi/operator:0.23.0'
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: 'quay.io/strimzi/operator:0.23.0'
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: 'quay.io/strimzi/operator:0.23.0'
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: 'quay.io/strimzi/kafka-bridge:0.19.0'
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: 'quay.io/strimzi/jmxtrans:0.23.0'
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: 'quay.io/strimzi/kaniko-executor:0.23.0'
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FEATURE_GATES
              value: ''
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-kafka-entity-operator
  labels:
    kubearmor-app: strimzi
rules:
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkatopics
      - kafkatopics/status
      - kafkausers
      - kafkausers/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-kafka-cluster-operator-global
  labels:
    kubearmor-app: strimzi
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-kafka-cluster-operator-kafka-broker-delegation
  labels:
    kubearmor-app: strimzi
subjects:
  - kind: ServiceAccount
    name: kubearmor-kafka-cluster-operator
    namespace: kubearmor
roleRef:
  kind: ClusterRole
  name: kubearmor-kafka-broker
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubearmor-kafka-cluster-operator
  namespace: kubearmor
  labels:
    kubearmor-app: strimzi
subjects:
  - kind: ServiceAccount
    name: kubearmor-kafka-cluster-operator
    namespace: kubearmor
roleRef:
  kind: ClusterRole
  name: kubearmor-kafka-cluster-operator-namespaced
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-kafka-cluster-operator-namespaced
  labels:
    kubearmor-app: strimzi
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - pods
      - serviceaccounts
      - configmaps
      - services
      - endpoints
      - secrets
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkas/status
      - kafkaconnects
      - kafkaconnects/status
      - kafkaconnects2is
      - kafkaconnects2is/status
      - kafkaconnectors
      - kafkaconnectors/status
      - kafkamirrormakers
      - kafkamirrormakers/status
      - kafkabridges
      - kafkabridges/status
      - kafkamirrormaker2s
      - kafkamirrormaker2s/status
      - kafkarebalances
      - kafkarebalances/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - extensions
    resources:
      - deployments
      - deployments/scale
      - replicasets
      - replicationcontrollers
      - networkpolicies
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
      - deployments/status
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
      - deploymentconfigs/scale
      - deploymentconfigs/status
      - deploymentconfigs/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
      - buildconfigs/instantiate
      - builds
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
      - imagestreams/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-kafka-topic-operator
  labels:
    kubearmor-app: strimzi
rules:
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkatopics
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-kafka-cluster-operator-kafka-client-delegation
  labels:
    kubearmor-app: strimzi
subjects:
  - kind: ServiceAccount
    name: kubearmor-kafka-cluster-operator
    namespace: kubearmor
roleRef:
  kind: ClusterRole
  name: kubearmor-kafka-client
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-kafka-client
  labels:
    kubearmor-app: strimzi
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubearmor-kafka-cluster-operator
  namespace: kubearmor
  labels:
    kubearmor-app: strimzi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-kafka-broker
  labels:
    kubearmor-app: strimzi
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubearmor-kafka-cluster-operator
  namespace: kubearmor
  labels:
    kubearmor-app: strimzi
data:
  log4j2.properties: >
    name = COConfig

    monitorInterval = 30


    appender.console.type = Console

    appender.console.name = STDOUT

    appender.console.layout.type = PatternLayout

    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L -
    %m%n


    rootLogger.level = ${env:STRIMZI_LOG_LEVEL:-INFO}

    rootLogger.appenderRefs = stdout

    rootLogger.appenderRef.console.ref = STDOUT

    rootLogger.additivity = false


    # Kafka AdminClient logging is a bit noisy at INFO level

    logger.kafka.name = org.apache.kafka

    logger.kafka.level = WARN

    logger.kafka.additivity = false


    # Zookeeper is very verbose even on INFO level -> We set it to WARN by
    default

    logger.zookeepertrustmanager.name = org.apache.zookeeper

    logger.zookeepertrustmanager.level = WARN

    logger.zookeepertrustmanager.additivity = false


    # Keeps separate level for Netty logging -> to not be changed by the root
    logger

    logger.netty.name = io.netty

    logger.netty.level = INFO

    logger.netty.additivity = false
